# Generated by Django 5.2.7 on 2025-10-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='appid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
