# Generated by Django 5.2.7 on 2025-10-27 16:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_developer_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
