# Generated by Django 5.2.7 on 2025-10-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userprofile_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='appid',
            field=models.IntegerField(blank=True, help_text='Steam AppID для превью header.jpg', null=True, unique=True),
        ),
    ]
