# Generated by ChatGPT on 2025-10-28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_order_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='supports_windows',
            field=models.BooleanField(default=False, help_text='Игра поддерживает Windows'),
        ),
        migrations.AddField(
            model_name='game',
            name='supports_mac',
            field=models.BooleanField(default=False, help_text='Игра поддерживает macOS'),
        ),
        migrations.AddField(
            model_name='game',
            name='supports_linux',
            field=models.BooleanField(default=False, help_text='Игра поддерживает Linux'),
        ),
    ]
