# Generated by Django 5.2.7 on 2025-11-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_platform_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sysreq_min',
            field=models.TextField(blank=True, default='', help_text='Минимальные системные требования (можно HTML)'),
        ),
        migrations.AddField(
            model_name='game',
            name='sysreq_rec',
            field=models.TextField(blank=True, default='', help_text='Рекомендуемые системные требования (можно HTML)'),
        ),
    ]
