# Generated by Django 5.2.7 on 2025-11-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_game_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sysreq_min',
            field=models.TextField(blank=True, help_text='Минимальные системные требования (можно HTML)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='sysreq_rec',
            field=models.TextField(blank=True, help_text='Рекомендуемые системные требования (можно HTML)'),
        ),
    ]
