# Generated by Copilot on 2025-11-07
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_game_sysreq_min_alter_game_sysreq_rec'),
    ]

    operations = [
        # This migration is intentionally left empty to resolve branch conflicts.
    ]
