# Generated by Django 5.2.7 on 2025-11-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('purchase', 'Проблема с покупкой/оплатой'), ('tech', 'Техническая проблема (загрузка, ошибки)'), ('account', 'Вопрос по аккаунту/профилю'), ('feedback', 'Обратная связь/предложение'), ('other', 'Другое')], default='tech', max_length=30),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='category_other',
            field=models.CharField(blank=True, help_text="Если выбрано 'Другое' — уточните тему", max_length=200),
        ),
    ]
