# Generated by Django 5.2.7 on 2025-11-05 21:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_supportticket_category_supportticket_category_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH'), ('GBP', 'GBP'), ('RUB', 'RUB'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('CNY', 'CNY'), ('PLN', 'PLN')], default='USD', max_length=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.game')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_snapshot', to='store.order')),
            ],
        ),
    ]
