# Generated by Django 5.2.7 on 2025-11-05 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_reviewvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['game', 'created_at'], name='store_revie_game_id_f522fe_idx'),
        ),
    ]
