# Generated by Django 5.2.7 on 2025-11-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_game_home_flags'),
        ('store', '0017_alter_review_rating'),
    ]

    operations = [
    ]
