# Generated by Django 5.2.7 on 2025-11-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_merge_0012_game_home_flags_0017_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bg_appid',
            field=models.IntegerField(blank=True, help_text='AppID игры для фонового баннера профиля (используется header.jpg)', null=True),
        ),
    ]
