# Generated by Django 5.2.7 on 2025-11-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_userprofile_bg_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy',
            field=models.CharField(choices=[('public', 'Публичный'), ('friends', 'Только друзья'), ('private', 'Только владелец')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_bg',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/backgrounds/'),
        ),
    ]
