# Generated by Django 5.2.7 on 2025-11-06 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_userprofile_privacy_userprofile_profile_bg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='steam_avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='steam_id',
            field=models.CharField(blank=True, help_text='SteamID64, если пользователь вошёл через Steam', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='steam_persona',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='OwnedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('steam', 'Steam'), ('manual', 'Manual')], default='steam', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='store.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game', 'source')},
            },
        ),
    ]
