# Generated by Django 5.2.7 on 2025-11-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_userprofile_steam_avatar_userprofile_steam_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedgame',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownedgame',
            name='playtime_2weeks',
            field=models.IntegerField(blank=True, help_text='Минут за последние 2 недели', null=True),
        ),
        migrations.AddField(
            model_name='ownedgame',
            name='playtime_forever',
            field=models.IntegerField(default=0, help_text='Минут всего по данным Steam'),
        ),
    ]
