# Generated by Django 5.2.7 on 2025-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_friend_events',
            field=models.BooleanField(default=False, help_text='Email о запросах/подтверждениях дружбы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_profile_comment',
            field=models.BooleanField(default=True, help_text='Присылать email о комментариях (если указан email)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_friend_accept',
            field=models.BooleanField(default=True, help_text='Уведомления, когда мою заявку принимают'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_friend_request',
            field=models.BooleanField(default=True, help_text='Уведомления о входящих заявках в друзья'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_profile_comment',
            field=models.BooleanField(default=True, help_text='Внутренние уведомления о новых комментариях на моём профиле'),
        ),
    ]
