# Generated by Django 5.2.7 on 2025-11-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_userprofile_email_friend_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_privacy',
            field=models.CharField(choices=[('public', 'Комментировать могут все'), ('friends', 'Только друзья'), ('nobody', 'Никто, кроме меня')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friend_request_privacy',
            field=models.CharField(choices=[('public', 'Все могут отправлять заявки'), ('friends', 'Только друзья друзей (упрощённо — как все)'), ('nobody', 'Никто')], default='public', max_length=10),
        ),
    ]
