# Generated by Django 5.2.8 on 2025-11-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_price_alerts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='currencyrate',
            new_name='store_curre_base_d1ab9b_idx',
            old_name='store_curre_base_ta_0a7b63_idx',
        ),
        migrations.RenameIndex(
            model_name='currencyrate',
            new_name='store_curre_fetched_fc95c1_idx',
            old_name='store_curre_fetched_4f8b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='pricesnapshot',
            new_name='store_price_game_id_6f998a_idx',
            old_name='store_price_game_id_snapsho_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='store_walle_user_id_a430ea_idx',
            old_name='store_walle_user_id_4c4d13_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='store_walle_user_id_a7b9b5_idx',
            old_name='store_walle_user_id_70887a_idx',
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('profile_comment', 'Комментарий в профиле'), ('friend_request', 'Заявка в друзья'), ('friend_accept', 'Дружба подтверждена'), ('price_drop', 'Снижение цены в списке желаемого')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Українська'), ('ru', 'Русский')], default='en', max_length=5),
        ),
    ]
