# Generated by Django 5.2.7 on 2025-11-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_userprofile_avatar'),
        ('store', '0035_userprofile_bio_theme'),
    ]

    operations = [
    ]
