# Generated by Django 5.2.7 on 2025-11-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_merge_20251108_bio_markdown_username_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friend_code',
            field=models.CharField(blank=True, help_text="Публичный код для добавления в друзья (вводится на странице 'Мои друзья')", max_length=16, null=True, unique=True),
        ),
    ]
