# Generated by Django 5.2.7 on 2025-11-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cleanup_sysreq_fields'),
        ('store', '0038_userprofile_friend_code'),
    ]

    operations = [
    ]
