# Generated by Django 5.2.7 on 2025-11-09 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_merge_sysreq_cleanup_with_existing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('profile_comment', 'Комментарий в профиле'), ('friend_request', 'Заявка в друзья'), ('friend_accept', 'Дружба подтверждена'), ('price_drop', 'Снижение цены в списке желаемого'), ('support_reply', 'Ответ поддержки')], max_length=32),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False, help_text='Сообщение отправлено сотрудником/администратором')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
