# Generated by Django 5.2.7 on 2025-11-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_notification_kind_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('profile_comment', 'Комментарий в профиле'), ('friend_request', 'Заявка в друзья'), ('friend_accept', 'Дружба подтверждена'), ('price_drop', 'Снижение цены в списке желаемого'), ('support_reply', 'Ответ поддержки'), ('support_new', 'Новое обращение в поддержку')], max_length=32),
        ),
    ]
