# Generated by Copilot on 2025-11-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_notification_support_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(
                choices=[
                    ('profile_comment', 'Комментарий в профиле'),
                    ('friend_request', 'Заявка в друзья'),
                    ('friend_accept', 'Дружба подтверждена'),
                    ('price_drop', 'Снижение цены в списке желаемого'),
                    ('support_reply', 'Ответ поддержки'),
                    ('support_new', 'Новое обращение в поддержку'),
                    ('support_created', 'Создано ваше обращение'),
                ],
                max_length=32,
            ),
        ),
    ]
