from django.urls import path
from .views import (
    GameListView,
    GameDetailView,
    HomeView,
    ProfileEditView,
    SettingsView,
    ProfileView,
    ProfileBadgesView,
    ProfileCommentCreateView,
    ProfileCommentDeleteView,
    ProfileCommentSubscriptionToggleView,
    FriendToggleView,
    FriendRequestRespondView,
    FriendsListView,
    SubscriptionsView,
    NotificationsView,
    ProfileCommentBanToggleView,
    SteamAuthStartView,
    ChartsView,
    RecommendationsView,
    RecommendationsHideView,
    LogoutView,
    AboutView,
    SearchSuggestView,
    WishlistListView,
    WishlistToggleView,
    RegisterView,
    CartAddView,
    CartView,
    CartUpdateView,
    CartRemoveView,
    CartClearView,
    CheckoutView,
    OrderDetailView,
    OrdersListView,
    PaymentView,
    LibraryView,
    DiscountsListView,
    SupportView,
    SupportTicketDetailView,
    SupportTicketListView,
    ReviewVoteView,
    MyReviewsView,
    ReviewDeleteView,
    ProfilePrefToggleView,
    LanguageSetView,
    WalletTopUpView,
    FriendAddByCodeView,
)
app_name = 'store'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    # Explicit edit page for profile appearance (avatar, theme, persona)
    path('profile/edit/', ProfileEditView.as_view(), name='profile_edit'),
    # New unified settings hub
    path('settings/<str:section>/', SettingsView.as_view(), name='settings'),
    path('settings/', SettingsView.as_view(), {'section': 'general'}, name='settings_default'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
    path('profile/<str:username>/badges/', ProfileBadgesView.as_view(), name='profile_badges'),
    path('profile/<str:username>/comment/', ProfileCommentCreateView.as_view(), name='profile_comment'),
    path('profile/<str:username>/comment_sub_toggle/', ProfileCommentSubscriptionToggleView.as_view(), name='profile_comment_sub_toggle'),
    path('profile/comment/delete/<int:pk>/', ProfileCommentDeleteView.as_view(), name='profile_comment_delete'),
    path('profile/<str:username>/friend_toggle/', FriendToggleView.as_view(), name='friend_toggle'),
    path('friends/', FriendsListView.as_view(), name='friends'),
    path('friends/add_by_code/', FriendAddByCodeView.as_view(), name='friend_add_by_code'),
    path('friend_request/respond/<int:pk>/', FriendRequestRespondView.as_view(), name='friend_request_respond'),
    path('subscriptions/', SubscriptionsView.as_view(), name='subscriptions'),
    path('notifications/', NotificationsView.as_view(), name='notifications'),
    path('profile/<str:username>/ban_toggle/<int:user_id>/', ProfileCommentBanToggleView.as_view(), name='profile_comment_ban_toggle'),
    path('auth/steam/', SteamAuthStartView.as_view(), name='auth_steam_start'),
    path('charts/', ChartsView.as_view(), name='charts'),
    path('about/', AboutView.as_view(), name='about'),
    path('recommendations/', RecommendationsView.as_view(), name='recommendations'),
    path('recommendations/hide/<int:pk>/', RecommendationsHideView.as_view(), name='recommendations_hide'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('api/search_suggest/', SearchSuggestView.as_view(), name='search_suggest'),
    path('games/', GameListView.as_view(), name='game_list'),
    path('discounts/', DiscountsListView.as_view(), name='discounts'),
    path('game/<slug:slug>/', GameDetailView.as_view(), name='game_detail'),
    path('wishlist/', WishlistListView.as_view(), name='wishlist'),
    path('wishlist/toggle/<slug:slug>/', WishlistToggleView.as_view(), name='wishlist_toggle'),
    path('cart/add/<slug:slug>/', CartAddView.as_view(), name='cart_add'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/update/<int:item_id>/', CartUpdateView.as_view(), name='cart_update'),
    path('cart/remove/<int:item_id>/', CartRemoveView.as_view(), name='cart_remove'),
    path('cart/clear/', CartClearView.as_view(), name='cart_clear'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('pay/<int:pk>/', PaymentView.as_view(), name='pay'),
    path('support/', SupportView.as_view(), name='support'),
    path('support/tickets/', SupportTicketListView.as_view(), name='support_tickets'),
    path('support/ticket/<int:pk>/', SupportTicketDetailView.as_view(), name='support_ticket'),
    path('reviews/vote/<int:pk>/', ReviewVoteView.as_view(), name='review_vote'),
    path('library/', LibraryView.as_view(), name='library'),
    path('profile/reviews/', MyReviewsView.as_view(), name='my_reviews'),
    path('reviews/delete/<int:pk>/', ReviewDeleteView.as_view(), name='review_delete'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    # Wallet
    path('wallet/topup/', WalletTopUpView.as_view(), name='wallet_topup'),
    # AJAX
    path('api/profile/pref-toggle/', ProfilePrefToggleView.as_view(), name='profile_pref_toggle'),
    path('api/lang/set/', LanguageSetView.as_view(), name='lang_set'),
]
